### ISSUE TITLE
KeyError: 'THEME' when running the app

### ISSUE THREAD

**Issue by Aklal** [encima/flask-task#2]
Hello, 
I have downloaded flask-task and I did everything specified in the README.
When I run the app I have the following error:

```
$ tf/bin/python run.py

Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app, db, models
  File "Documents/TaskWarriorWeb/flask-task-master/app/__init__.py", line 18, in <module>
    from app.views import views  # noqa
  File "Documents/TaskWarriorWeb/flask-task-master/app/views.py", line 15, in <module>
    theme = app.config['THEME'].lower()
KeyError: 'THEME'
```

During the installation I had some warnings but I guess it is not the root of the problem:

```
$ tf/bin/pip install -r requirements.txt
Collecting Babel==2.3.4 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b4/ec/acd307eac2e23f9cab1c8bdbe29b3b1d43215e31c32f8aa91b3a97925b5b/Babel-2.3.4-py2.py3-none-any.whl (7.1MB)
     |████████████████████████████████| 7.1MB 2.6MB/s
Collecting backports-abc==0.4 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/f5/5e/57e1afdc63d8c37496b2f6d9cb0ddfc4a3d55c949074debeab7594c19b54/backports_abc-0.4-py2.py3-none-any.whl
Collecting backports.ssl-match-hostname==3.5.0.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/76/21/2dc61178a2038a5cb35d14b61467c6ac632791ed05131dda72c20e7b9e23/backports.ssl_match_hostname-3.5.0.1.tar.gz
Collecting certifi==2016.2.28 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/db/60/1ed0106bde7b14b363b15b17cc308aad93ba57d3582570f3ad7180ae0fae/certifi-2016.2.28-py2.py3-none-any.whl (366kB)
     |████████████████████████████████| 368kB 47.3MB/s
Collecting Flask==0.10.1 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/db/9c/149ba60c47d107f85fe52564133348458f093dd5e6b57a5b60ab9ac517bb/Flask-0.10.1.tar.gz (544kB)
     |████████████████████████████████| 552kB 49.1MB/s
Collecting Flask-Admin==1.4.0 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/c6/ca/f31d4cc4112624c8af348f7e2b5e539acabbd7db002dcd3f8aa1f611397e/Flask-Admin-1.4.0.tar.gz (868kB)
     |████████████████████████████████| 870kB 44.7MB/s
Collecting Flask-Login==0.3.2 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/06/e6/61ed90ed8ce6752b745ed13fac3ba407dc9db95dfa2906edc8dd55dde454/Flask-Login-0.3.2.tar.gz
Collecting Flask-SQLAlchemy==2.1 (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/b3/52/227aaf4e8cebb153e239c518a9e916590b2fe0e4350e6b02d92b546b69b7/Flask-SQLAlchemy-2.1.tar.gz (95kB)
     |████████████████████████████████| 102kB 28.2MB/s
Collecting Flask-Table==0.2.10 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/25/f4/015004e6ebdcd145fbc92cd46535da631631ced1e83422170ab170bc31b6/Flask-Table-0.2.10.tar.gz
Collecting itsdangerous==0.24 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz (46kB)
     |████████████████████████████████| 51kB 22.4MB/s
Collecting Jinja2==2.8 (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/96/a1/c56bc4d99dc2663514a8481511e80eba8994133ae75eebdadfc91a5597d9/Jinja2-2.8-py2.py3-none-any.whl (263kB)
     |████████████████████████████████| 266kB 49.4MB/s
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/c0/41/bae1254e0396c0cc8cf1751cb7d9afc90a602353695af5952530482c963f/MarkupSafe-0.23.tar.gz
Collecting passlib==1.6.5 (from -r requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/2d/a7/1a3363e5d531d438267a79d43d4b8d224655adef489e98fc96678fe16ed1/passlib-1.6.5-py2.py3-none-any.whl (317kB)
     |████████████████████████████████| 327kB 49.7MB/s
Collecting python-dateutil==2.5.3 (from -r requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/33/68/9eadc96f9899caebd98f55f942d6a8f3fb2b8f8e69ba81a0f771269897e9/python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
     |████████████████████████████████| 204kB 26.5MB/s
Collecting pytz==2016.4 (from -r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/ae/cf/a7442138ad899a7587489641a8923f1e640cafc2d6ffe4e79e5d15cc5b3e/pytz-2016.4-py2.py3-none-any.whl (480kB)
     |████████████████████████████████| 481kB 61.5MB/s
Collecting singledispatch==3.4.0.3 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting six==1.10.0 (from -r requirements.txt (line 17))
  Downloading https://files.pythonhosted.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting SQLAlchemy==1.0.12 (from -r requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/5c/52/9b48cd58eac58cae2a27923ff34c783f390b95413ff65669a86e98f80829/SQLAlchemy-1.0.12.tar.gz (4.7MB)
     |████████████████████████████████| 4.8MB 52.3MB/s
Collecting tabulate==0.7.5 (from -r requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/db/40/6ffc855c365769c454591ac30a25e9ea0b3e8c952a1259141f5b9878bd3d/tabulate-0.7.5.tar.gz
Collecting taskw==1.1.0 (from -r requirements.txt (line 20))
  Downloading https://files.pythonhosted.org/packages/af/40/513f8323d2864566f5530a8052371a06c6510229d955a1f69248889a9be4/taskw-1.1.0.tar.gz
Collecting tornado==4.3 (from -r requirements.txt (line 21))
  Downloading https://files.pythonhosted.org/packages/21/29/e64c97013e97d42d93b3d5997234a6f17455f3744847a7c16289289f8fa6/tornado-4.3.tar.gz (450kB)
     |████████████████████████████████| 460kB 42.6MB/s
Collecting Werkzeug==0.11.4 (from -r requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/a8/6a/12dca42596ffa19297bd31154b489c5dd5ab3399850644894de10e7bbcae/Werkzeug-0.11.4-py2.py3-none-any.whl (305kB)
     |████████████████████████████████| 307kB 36.7MB/s
Collecting WTForms==2.1 (from -r requirements.txt (line 23))
  Downloading https://files.pythonhosted.org/packages/bf/91/2e553b86c55e9cf2f33265de50e052441fb753af46f5f20477fe9c61280e/WTForms-2.1.zip (553kB)
     |████████████████████████████████| 563kB 62.6MB/s
Collecting flask_script (from -r requirements.txt (line 24))
  Downloading https://files.pythonhosted.org/packages/00/a4/cd587b2b19f043b65bf33ceda2f6e4e6cdbd0ce18d01a52b9559781b1da6/Flask-Script-2.0.6.tar.gz (43kB)
     |████████████████████████████████| 51kB 21.3MB/s
Building wheels for collected packages: backports.ssl-match-hostname, Flask, Flask-Admin, Flask-Login, Flask-SQLAlchemy, Flask-Table, itsdangerous, MarkupSafe, SQLAlchemy, tabulate, taskw, tornado, WTForms, flask-script
  WARNING: Building wheel for backports.ssl-match-hostname failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/99'
  WARNING: Building wheel for Flask failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/e1'
  WARNING: Building wheel for Flask-Admin failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/94'
  WARNING: Building wheel for Flask-Login failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/96'
  WARNING: Building wheel for Flask-SQLAlchemy failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/bd'
  WARNING: Building wheel for Flask-Table failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/4e'
  WARNING: Building wheel for itsdangerous failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/2c'
  WARNING: Building wheel for MarkupSafe failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/28'
  WARNING: Building wheel for SQLAlchemy failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/01'
  WARNING: Building wheel for tabulate failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/96'
  WARNING: Building wheel for taskw failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/9e'
  WARNING: Building wheel for tornado failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/00'
  WARNING: Building wheel for WTForms failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/ab'
  WARNING: Building wheel for flask-script failed: [Errno 13] Permission denied: '/Users/max/Library/Caches/pip/wheels/1c'
Failed to build backports.ssl-match-hostname Flask Flask-Admin Flask-Login Flask-SQLAlchemy Flask-Table itsdangerous MarkupSafe SQLAlchemy tabulate taskw tornado WTForms flask-script
Installing collected packages: pytz, Babel, backports-abc, backports.ssl-match-hostname, certifi, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, WTForms, Flask-Admin, Flask-Login, SQLAlchemy, Flask-SQLAlchemy, Flask-Table, passlib, six, python-dateutil, singledispatch, tabulate, taskw, tornado, flask-script
  Running setup.py install for backports.ssl-match-hostname ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for itsdangerous ... done
  Running setup.py install for Flask ... done
  Running setup.py install for WTForms ... done
  Running setup.py install for Flask-Admin ... done
  Running setup.py install for Flask-Login ... done
  Running setup.py install for SQLAlchemy ... done
  Running setup.py install for Flask-SQLAlchemy ... done
  Running setup.py install for Flask-Table ... done
  Running setup.py install for tabulate ... done
  Running setup.py install for taskw ... done
  Running setup.py install for tornado ... done
  Running setup.py install for flask-script ... done
Successfully installed Babel-2.3.4 Flask-0.10.1 Flask-Admin-1.4.0 Flask-Login-0.3.2 Flask-SQLAlchemy-2.1 Flask-Table-0.2.10 Jinja2-2.8 MarkupSafe-0.23 SQLAlchemy-1.0.12 WTForms-2.1 Werkzeug-0.11.4 backports-abc-0.4 backports.ssl-match-hostname-3.5.0.1 certifi-2016.2.28 flask-script-2.0.6 itsdangerous-0.24 passlib-1.6.5 python-dateutil-2.5.3 pytz-2016.4 singledispatch-3.4.0.3 six-1.10.0 tabulate-0.7.5 taskw-1.1.0 tornado-4.3
```

Thanks in advance

**Comment by encima** [comment]
It really has been years since I have worked on this (although I keep meaning to find time), but it seems like this is because the `THEME` var is not set in the `sample.cfg` file.

I have added it now but, if you are using a different theme than `base`, you will also need to change it. Probably a default value should be set in the app...

**Comment by encima** [comment]
Closing due to inactivity (yes, I know a bot should do that). Feel free to reopen or create a new issue if you have further problems.
